[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../shared", default-features = false }
lightyear.workspace = true
lightyear_avian.workspace = true
bevy.workspace = true
avian3d.workspace = true
